### ISSUE TITLE
Item History 'Tab' showing as "Not Found (404)"

### ISSUE THREAD

**Issue by skwlilac** [UKGovLD/registry-core#150]
A recent update to registry-core appears to have broken either the retrieval or the rendering of item history.

To reproduce visit of these pages and click the "History" link on the RHS of the page:

https://data.food.gov.uk/codes/geographies/countries/_AF
https://environment.data.gov.uk/registry/def/catchment-planning/RiverBasinDistrict/_UK05

Backtracking through the commit history reveals that the bug was introduced between commits f6a6680 and bedd729.

The only significant change between these two commits is a dependency version change for `appbase` from `3.1.0` to `3.1.1` which appears to be intended to address an XSS issue. 

The commit message on bedd729 says:

> Fix XSS inject of uri param
>
> Updates to appbase release which prevents injection of uri param into velocity context

**Comment by skwlilac** [comment]
Confirm that locally rebuilding using appbase `3.1.0` resolves the presenting problem (but obviously removes the XSS fix introduced by `3.1.1`).

**Comment by der** [comment]
So the issue is the velocity parameter `$uri` is used in most places in the template to represent the relative URI of the page being rendered. The templates assume this is safe and do not sanitise it since it is generated as part of the velocity filter in `appbase` itself.

Prior to appbase `3.1.1` we mistakenly allowed a query parameter called `uri` to override the normal setting of that variable and so were open to an injection attack. The appbase change prevents that override entirely.

However, the showhistory function is the one place that relied on the `uri` query parameter to pass the URI of the entity whose history is being rendered down to the `showhistory.vm` template. In retrospect, that was a design error.

Suggested fix is to change `showhistory.vm` and `ui.js` in `registry-config-base` to use a different query parameter and sanitise _that_ parameter where used in the template. This would mean that any deployed applications will need to update their template and js files to match.

Alternative would be to unblock `uri` as a query parameter but force sanitation of it in `appbase` which would avoid the need to update templates but feels like a cludge that would propagates the design error.

**Comment by der** [comment]
Fixed by linked change to `registry-config-base`
