### ISSUE TITLE
[2.3.7] issue with registry.language.manager on a fresh deployment

### ISSUE THREAD

**Issue by sgrellet** [UKGovLD/registry-core#156]
Deploying the latest version on Docker we have the following situation on a fresh installation with the following conf (screeshot below).

The deployment goes on but we end-up with "Template rendering problem: java.lang.NullPointerException" when accessing the application

Work-around : launching the 1st deployment with the line "registry.languageManager=$langManager" commented then redeploying on the same VM with the line uncommented. -> it works

Have you already faced this ?

Assumptions
- too short timeout in our system to obtain all the dependencies
- something is blocked at web application firewall / conf / nginx level on a fresh installation that is allowed on a 2nd deployment
- deployment needs dependencies from com.epimorphics.lang which the server cannot obtain the 1st time

![image](https://user-images.githubusercontent.com/16756304/149950608-942f8d7d-89e2-47ff-9b42-dd9c73ae6cd9.png)

**Comment by simonoakesepimorphics** [comment]
I've attempted to replicate by just setting up a registry with the language manager but I haven't succeeded. Please can you provide the application log (including stack trace)?

The language components are all part of the registry core package so I wouldn't expect there to be any dependency issues.  It's driven by the language register and the language files in your registry config directory, so as a sanity check I advise you to make sure that they are in a good state and the files are properly mounted in the Docker image/container.

**Comment by sgrellet** [comment]
Sorry for the latency, so far looking at the logs their is no detailled stack trace at the time of the exception. We are tweaking the conf to see more (see #157).
But it seems we managed to identify the steps to reproduce the error.
Note : V 2.3.7
1a°/ langManager activated in the conf, connecting to the tool with browser doing conneg in 'en' -> ok (event if no language register loaded).
2°/ setting the browser to do conneg in French and connecting to the main page -> nullPointerException


additionnal info 1b°/ if after 1a°/ we add the language register ('en' and 'fr'), flags for changing languages appear and changes languages works smoothly (note : it's still with conneg initially set to en in the browser)
https://github.com/tendrie : feel free to add more

**Comment by der** [comment]
Just noting that @simonoakesepimorphics, the best person to look at this, is tied up all week so there'll be a delay in responding.

**Comment by sgrellet** [comment]
Thanks @der for the info

**Comment by tendrie** [comment]
Hi,
Since the last ticket, we couldn't manage to make the first instanciation of lang (language register existed). We still have to specify in the url ?lang=fr or ?lang=en, at the first time we open the page. Then, the problem doesn't occur anymore.

Here I'm giving you the scenario with the corresponding log:

1) Enter the url without specifying the lang variable in the url (default browser language settings set to "en" )
![page_with_null](https://user-images.githubusercontent.com/14838277/151946185-e3956adc-2b47-425d-94fb-38e038d755d3.JPG)

Having the log

![log_with_null pointer](https://user-images.githubusercontent.com/14838277/151946249-44674cec-1c7b-4f5a-9756-42d3b4d3a22b.JPG)


2) Add variable lang=fr (or "en", it also works )


![page_with_lang](https://user-images.githubusercontent.com/14838277/151946338-0a1d6649-1cd6-4189-9831-ac7df502eb11.JPG)


We have set the log level to debug but we couldn't find more details about the error .
To reproduce the error, one only has to close and reopen the browser .

Our intuition is the first instantiation of $lang variable, because after the first page, there is no need to specify it in the URL anymore.

**Comment by simonoakesepimorphics** [comment]
This is fixed in version 2.3.8.

**Comment by sgrellet** [comment]
Thx, on our way to test this.

**Comment by sgrellet** [comment]
We deployed 2.3.8 and tested it succesfully here. Merci
