### ISSUE TITLE
Add registration form - need 'delegated' without 'namespace forward'

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#32]
The 'Add registration' capability in the UI has an option for 'forward'. 
Would be helpful to have one for just 'delegated'.

**Comment by der** [comment]
The UI doesn't provide for all the delegation modes, those require generating a suitable spec and uploading it. 

This is partly because the UI being too complex already and partly the practical value of those modes is unclear. The forwarding mode seems to be the main one that is used.

Could we clarify or close this issue?

**Comment by dr-shorthair** [comment]
I understand the design better now, so don't think this is required after all.
