### ISSUE TITLE
Search over more properties

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#34]
The LDR 'search' function (confusingly given the key "_query") appears to be scoped to rdfs:label, and perhaps the skos:*Label values. Suggest that the following fields should also be indexed by default:

dc:description
dc:source
dc:subject
dct:description
dct:subject
rdfs:comment
skos:definition
skos:note
skos:scopeNote

**Comment by der** [comment]
This can now be set per-deployment: https://github.com/UKGovLD/registry-core/wiki/Configuration#basestore

**Comment by dr-shorthair** [comment]
services.conf is still in the config directory. Will that be cleaned out? 
(Also see a bewilderingly large set of .vm's in templates/ - is there also some cruft here?

**Comment by der** [comment]
services.conf is there so that current registry-core.wars will (should) continue to function if deployed against this config. Could indeed be removed once the transition to the new layout is complete.

There may be some cruft .vm files but don't think there are many. It's almost certainly the vm could be renamed and restructured to be clearer now the functionality is a bit more stable. Would be useful but well below the cut line at the moment.
