### ISSUE TITLE
Inconsistent recording of 'who changed it' information in lifecycle record. 

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#51]
It appears that, while the information regarding 'who' submitted a register item is recorded, who made changes is not. 

This looks inconsistent to me. If the thinking is that it is not necessary to record 'who' modified an item since it is, by definition, the 'Register Manager', then submission information is also not required.

**Comment by der** [comment]
As noted on #52 the original thinking was that recording who did what when is achieved by logging and not by inspectable metadata. Submission is singled because it is possible to have registers which are open to anyone to submit to and who submitted is key information in deciding how to respond. 

Once you are beyond the "submitted" stage you are into the normal lifecyle with only a small number of people able to carry out actions.

It is clearly possible to change this and record all actions in the store using e.g. PROV-O and make that metadata both queriable and inspectable through a UI. That would be a fairly straightforward extension. Though that would further multiply the ratio of metadata to actual information in the registry.

One of our original design principles was that the registry itself should not be a complete workflow engine. It's job is to record and present the registered item and associated metadata. Workflow to route requests between people, have meetings to decide on the status of items, action people to carry out changes and track those actions should be done by separate tools. Recording who actually made the final edit in the registry falls in a grey area. If it is just for audit purposes then the logs may suffice. If it is for provenance and trace back then perhaps it should be part of that wider workflow management and recording system.

**Comment by dr-shorthair** [comment]
Fair enough. No hobgoblins here.
