### ISSUE TITLE
Refs to locally managed ontology causing various issues and crashes

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-core#59]
Here's the sequence: 

1. register a small ontology, containing classes and properties with # URIs, in a normal register 
 -- http://registry.it.csiro.au/ont 

2. register a Link definition, into /system/links, for one of the properties defined in this ontology 
 -- link definition is not used by an item that has such properties
 -- meanwhile, various parts of the UI get screwed up - missing information, tabs don't pop-up, in an odd mixture of locations, but particularly in the system registers

3. attempt to register a namespace prefix for the ontology in /system/prefixes
 -- major melt-down of whole Registry, does not revive itself. 

HTTP Status 500 - org.apache.velocity.exception.MethodInvocationException: Invocation of method 'wrap' in class com.epimorphics.registry.webapi.LibReg threw exception com.hp.hpl.jena.shared.PrefixMapping$IllegalPrefixException: 3cea65f3-8912-4d76-8ae2-5d011efbb2e2 at page-category.vm[line 56, column 38] 

Something about looping back references? 
the # URIs ?

Will send you a zip file with offending files.

**Comment by der** [comment]
I get the same behaviour at step 2 and can fix. However, for me step 3 causes no further problems.

What's the exact option you tried in step 3?

**Comment by dr-shorthair** [comment]
I just reproduced the problem by trying to upload the following to system/prefixes - 
(this time I did it in a test machine so can kill the result.) 

@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix dct:  <http://purl.org/dc/terms/> .
@prefix dc:   <http://purl.org/dc/elements/1.1/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix skosxl: <http://www.w3.org/2008/05/skos-xl#> .
@prefix version:  <http://purl.org/linked-data/version#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix ssd:  <http://www.w3.org/ns/sparql-service-description#> .
@prefix vs:   <http://www.w3.org/2003/06/sw-vocab-status/ns#> .
@prefix void: <http://rdfs.org/ns/void#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix time: <http://www.w3.org/2006/time#> .
@prefix api:  <http://purl.org/linked-data/api/vocab#> .
@prefix vann: <http://purl.org/vocab/vann/> .
@prefix reg:  <http://purl.org/linked-data/registry#> .
@prefix ui:   <http://purl.org/linked-data/registry-ui#> .
@prefix qb:      <http://purl.org/linked-data/cube#> .
@prefix org:  <http://www.w3.org/ns/org#> .
@prefix odrs: <http://schema.theodi.org/odrs#> .
@prefix dtr: <http://registry.it.csiro.au/ont/dxr#> .

<http://registry.it.csiro.au/ont/dxr#> a owl:Ontology;
    rdfs:label "dxr"@en;
    dct:description "dxr prefix registration - properties from the DXR ontology"@en;
    vann:preferredNamespacePrefix "dxr";
    vann:preferredNamespaceUri "http://registry.it.csiro.au/ont/dxr#";
    .

**Comment by der** [comment]
Thanks, still worked for me until I restarted with clean installation. Looks like first error was masking second.

**Comment by der** [comment]
First issue (error at step 2) arises because the ui-links declaration refers to a prefix which doesn't yet exist. I've modified the underlying library so that such errors are trapped and logged instead of throwing a UI-breaking exception.

Also generalized the handling of ui-links so that `ui:path` can be a resource (corresponding to a forward link) as well as a string giving a path. Note that you can use strings like "<http://mydomain/property>" in cases where you don't have a prefix.

The second error was due to an illegal prefix declarations being generated. The prefixes are used are several points in the registry processing so an illegal set of prefix declarations is fatal. The code had been using the notation for the entries in /system/prefixes as the prefix. In the error case the URI did not match the register so it was registered as an external entity. Since there was no notation value derivable it used a bnode and hence the notation looks like "3cea65f3-8912-4d76-8ae2-5d011efbb2e2" which is legal in a register but isn't a legal prefix.

Dealt with this by validating prefixes before they are used internally. A broken prefix is omitted and logged rather than crashing the processing. Also allowed for cases like this where the notation value is not a legal prefix but the entity has an explicit vann:preferredNamespacePrefix declaration which can be used instead. So in fact in this case the breaking entry is now valid.

New SNAPSHOT war available from: https://s3-eu-west-1.amazonaws.com/ukgovld/snapshot/com/github/ukgovld/registry-core/1.0.0-SNAPSHOT/registry-core-1.0.0-20150531.111741-3.war
